# Generated by Django 2.0.2 on 2018-02-04 12:52

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='risk_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fname', models.CharField(max_length=255)),
                ('date_fvalue', models.DateField()),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='riskapp.risk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='risk_enum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enum_fname', models.CharField(max_length=255)),
                ('enum_fvalue', django_mysql.models.EnumField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3')])),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='riskapp.risk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='risk_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_fname', models.CharField(max_length=255)),
                ('num_fvalue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='riskapp.risk')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='risk_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_fname', models.CharField(max_length=255)),
                ('text_fvalue', models.CharField(max_length=255)),
                ('risk_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='riskapp.risk')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
