# Generated by Django 2.0.2 on 2018-02-06 06:52

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('riskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='risk_fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', django_mysql.models.EnumField(choices=[('date', 'date'), ('enum', 'enum'), ('num', 'num'), ('text', 'text')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='risk_date',
            name='risk_type',
        ),
        migrations.RemoveField(
            model_name='risk_enum',
            name='risk_type',
        ),
        migrations.RemoveField(
            model_name='risk_num',
            name='risk_type',
        ),
        migrations.RemoveField(
            model_name='risk_text',
            name='risk_type',
        ),
        migrations.RenameModel(
            old_name='risk',
            new_name='risk_types',
        ),
        migrations.DeleteModel(
            name='risk_date',
        ),
        migrations.DeleteModel(
            name='risk_enum',
        ),
        migrations.DeleteModel(
            name='risk_num',
        ),
        migrations.DeleteModel(
            name='risk_text',
        ),
        migrations.AddField(
            model_name='risk_fields',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='riskapp.risk_types'),
        ),
    ]
